import { TemplateOption } from "../types/types";
import { t } from "../lang/helpers";

export const GENERATOR_VIEW_TYPE = "ioto-template-generator-view";

export const IOTO_VARIABLES = {
	input: `const {inputFolder, LTDListInputSectionHeading, LTDListOutputSectionHeading, taskFolder, useUserTemplate, addLinkToCurrentTDL, defaultTDLDateFormat, inputSelectorExcludesPaths, inputSelectorShowOptionOrder, inputSelectorShowBasePath, inputSelectorFolderOptionTemplate, newInputNoteFollowUpAction, inputNoteNamePrefix, inputNoteNamePostfix, inputNoteDefaultExcalidrawTemplate, defaultTDLHeadingLevel, newInputNoteAddedToTDLFollowUpAction} = app.plugins.plugins["ioto-settings"].settings;`,
	output: `const {outputFolder, LTDListOutcomeSectionHeading, LTDListOutputSectionHeading, taskFolder, useUserTemplate, addLinkToCurrentTDL, defaultTDLDateFormat, outputSelectorExcludesPaths, outputSelectorShowOptionOrder, outputSelectorShowBasePath, outputSelectorFolderOptionTemplate, newOutputNoteFollowUpAction, fleetingNoteFolder, fleetingNotePrefix, fleetingNoteDateFormat, outputNoteNamePrefix, outputNoteNamePostfix, outputNoteDefaultExcalidrawTemplate, defaultTDLHeadingLevel, newOutputNoteAddedToTDLFollowUpAction} = app.plugins.plugins["ioto-settings"].settings;`,
	task: `const {taskFolder, useUserTemplate, defaultTDLDateFormat, projectNameFormat, taskSelectorExcludesPaths, taskSelectorShowOptionOrder, taskSelectorShowBasePath, taskSelectorFolderOptionTemplate, taskSelectorEnableFutureDaysChoices, taskSelectorUseCustomTdlNames} = app.plugins.plugins["ioto-settings"].settings;`,
	outcome: `const {outcomeFolder, taskFolder, LTDListOutcomeSectionHeading, useUserTemplate, addLinkToCurrentTDL, defaultTDLDateFormat, outcomeSelectorExcludesPaths, outcomeSelectorShowOptionOrder, outcomeSelectorShowBasePath, outcomeSelectorFolderOptionTemplate, outcomeSelectorIncludeParentFolder, outcomeProjectDefaultSubFolders, newOutcomeNoteFollowUpAction, outcomeNoteNamePrefix, outcomeNoteNamePostfix, outcomeNoteDefaultExcalidrawTemplate, defaultTDLHeadingLevel, newOutcomeNoteAddedToTDLFollowUpAction} = app.plugins.plugins["ioto-settings"].settings;`,
	custom: `const {inputFolder, outputFolder, taskFolder, outcomeFolder, extraFolder, IOTOFrameworkPath} = app.plugins.plugins["ioto-settings"].settings;`,
};

export const IOTO_NOTE_TEMPLATES = {
	input: `const switcherTemplate = await tp.user.IOTOLoadTemplate(tp, tR, this.app, ml.t("IOTODefaultInputSwitcherTemplate"), false);`,
	output: `const switcherTemplate = await tp.user.IOTOLoadTemplate(tp, tR, this.app, ml.t("IOTODefaultOutputSwitcherTemplate"), false);`,
	task: `const switcherTemplate = await tp.user.IOTOLoadTemplate(tp, tR, this.app, ml.t("IOTODefaultTaskSwitcherTemplate"), false);`,
	outcome: `const switcherTemplate = await tp.user.IOTOLoadTemplate(tp, tR, this.app, ml.t("IOTODefaultOutcomeSwitcherTemplate"), false);`,
	custom: `const switcherTemplate = ""`,
};

export const IOTO_ML = `const ml = new (tp.user.IOTOMultiLangs(tp))(tp);`;

export const TEMPLATE_OPTIONS: TemplateOption[] = [
	{
		name: "addLinkToTDL",
		title: t("ADD_LINK_TO_TDL"),
		type: "Selector",
		for: "Input",
		order: 6,
		level: "Note",
		valueType: "boolean",
		defaultValue: true,
		description: t("INPUT_ADD_LINK_TO_TDL_DESC"),
		example: t("INPUT_ADD_LINK_TO_TDL_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "addLinkToTDL",
		title: t("ADD_LINK_TO_TDL"),
		type: "Selector",
		for: "Output",
		order: 6,
		level: "Note",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTPUT_ADD_LINK_TO_TDL_DESC"),
		example: t("OUTPUT_ADD_LINK_TO_TDL_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "addLinkToTDL",
		title: t("ADD_LINK_TO_TDL"),
		type: "Selector",
		for: "Outcome",
		order: 6,
		level: "Note",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTCOME_ADD_LINK_TO_TDL_DESC"),
		example: t("OUTCOME_ADD_LINK_TO_TDL_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "assignedNoteName",
		title: t("ASSIGNED_NOTE_NAME"),
		type: "Selector",
		for: "Input",
		order: 2,
		level: "Note",
		valueType: "string",
		defaultValue: '${tp.file.selection() ? tp.file.selection() : ""}',
		description: t("INPUT_ASSIGNED_NOTE_NAME_DESC"),
		example: t("INPUT_ASSIGNED_NOTE_NAME_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "assignedNoteName",
		title: t("ASSIGNED_NOTE_NAME"),
		type: "Selector",
		for: "Output",
		order: 2,
		level: "Note",
		valueType: "string",
		defaultValue: '${tp.file.selection() ? tp.file.selection() : ""}',
		description: t("OUTPUT_ASSIGNED_NOTE_NAME_DESC"),
		example: t("OUTPUT_ASSIGNED_NOTE_NAME_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "assignedNoteName",
		title: t("ASSIGNED_NOTE_NAME"),
		type: "Selector",
		for: "Outcome",
		order: 2,
		level: "Note",
		valueType: "string",
		defaultValue: '${tp.file.selection() ? tp.file.selection() : ""}',
		description: t("OUTCOME_ASSIGNED_NOTE_NAME_DESC"),
		example: t("OUTCOME_ASSIGNED_NOTE_NAME_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "assignedNoteName",
		title: t("ASSIGNED_NOTE_NAME"),
		type: "Selector",
		for: "Custom",
		order: 2,
		level: "Note",
		valueType: "string",
		defaultValue: '${tp.file.selection() ? tp.file.selection() : ""}',
		description: t("CUSTOM_ASSIGNED_NOTE_NAME_DESC"),
		example: t("CUSTOM_ASSIGNED_NOTE_NAME_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultExcalidrawTemplate",
		title: t("DEFAULT_EXCALIDRAW_TEMPLATE"),
		type: "Selector",
		for: "Custom",
		order: 6,
		level: "Note",
		valueType: "file",
		defaultValue: "",
		description: t("CUSTOM_DEFAULT_EXCALIDRAW_TEMPLATE_DESC"),
		example: t("CUSTOM_DEFAULT_EXCALIDRAW_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultExcalidrawTemplate",
		title: t("DEFAULT_EXCALIDRAW_TEMPLATE"),
		type: "Selector",
		for: "Input",
		order: 7,
		level: "Note",
		valueType: "file",
		defaultValue: "${inputNoteDefaultExcalidrawTemplate}",
		description: t("INPUT_DEFAULT_EXCALIDRAW_TEMPLATE_DESC"),
		example: t("INPUT_DEFAULT_EXCALIDRAW_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultExcalidrawTemplate",
		title: t("DEFAULT_EXCALIDRAW_TEMPLATE"),
		type: "Selector",
		for: "Output",
		order: 7,
		level: "Note",
		valueType: "file",
		defaultValue: "${outputNoteDefaultExcalidrawTemplate}",
		description: t("OUTPUT_DEFAULT_EXCALIDRAW_TEMPLATE_DESC"),
		example: t("OUTPUT_DEFAULT_EXCALIDRAW_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultExcalidrawTemplate",
		title: t("DEFAULT_EXCALIDRAW_TEMPLATE"),
		type: "Selector",
		for: "Outcome",
		order: 7,
		level: "Note",
		valueType: "file",
		defaultValue: "${outcomeNoteDefaultExcalidrawTemplate}",
		description: t("OUTCOME_DEFAULT_EXCALIDRAW_TEMPLATE_DESC"),
		example: t("OUTCOME_DEFAULT_EXCALIDRAW_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultNewNoteFollowUpAction",
		title: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION"),
		type: "Selector",
		for: "Input",
		order: 5,
		level: "Note",
		valueType: "integer",
		defaultValue: 1,
		asSelector: true,
		choices: [
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_0"),
				value: 0,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_1"),
				value: 1,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_2"),
				value: 2,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_3"),
				value: 3,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_4"),
				value: 4,
			},
		],
		description: t("INPUT_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_DESC"),
		example: t("INPUT_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultNewNoteFollowUpAction",
		title: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION"),
		type: "Selector",
		for: "Output",
		order: 5,
		level: "Note",
		valueType: "integer",
		defaultValue: 1,
		asSelector: true,
		choices: [
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_0"),
				value: 0,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_1"),
				value: 1,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_2"),
				value: 2,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_3"),
				value: 3,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_4"),
				value: 4,
			},
		],
		description: t("OUTPUT_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_DESC"),
		example: t("OUTPUT_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultNewNoteFollowUpAction",
		title: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION"),
		type: "Selector",
		for: "Outcome",
		order: 5,
		level: "Note",
		valueType: "integer",
		defaultValue: 1,
		asSelector: true,
		choices: [
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_0"),
				value: 0,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_1"),
				value: 1,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_2"),
				value: 2,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_3"),
				value: 3,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_4"),
				value: 4,
			},
		],
		description: t("OUTCOME_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_DESC"),
		example: t("OUTCOME_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "defaultNewNoteFollowUpAction",
		title: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION"),
		type: "Selector",
		for: "Custom",
		order: 5,
		level: "Note",
		valueType: "integer",
		defaultValue: 1,
		asSelector: true,
		choices: [
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_0"),
				value: 0,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_1"),
				value: 1,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_2"),
				value: 2,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_3"),
				value: 3,
			},
			{
				label: t("DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_OPTION_4"),
				value: 4,
			},
		],
		description: t("CUSTOM_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_DESC"),
		example: t("CUSTOM_DEFAULT_NEW_NOTE_FOLLOW_UP_ACTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "enableFutureDaysChoices",
		title: t("ENABLE_FUTURE_DAYS_CHOICES"),
		type: "Selector",
		for: "Task",
		order: 5,
		level: "Note",
		valueType: "boolean",
		defaultValue: false,
		description: t("TASK_ENABLE_FUTURE_DAYS_CHOICES_DESC"),
		example: t("TASK_ENABLE_FUTURE_DAYS_CHOICES_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "excludesPaths",
		title: t("EXCLUDES_PATHS"),
		type: "Selector",
		for: "Input",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("INPUT_EXCLUDES_PATHS_DESC"),
		example: t("INPUT_EXCLUDES_PATHS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "excludesPaths",
		title: t("EXCLUDES_PATHS"),
		type: "Selector",
		for: "Output",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("OUTPUT_EXCLUDES_PATHS_DESC"),
		example: t("OUTPUT_EXCLUDES_PATHS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "excludesPaths",
		title: t("EXCLUDES_PATHS"),
		type: "Selector",
		for: "Outcome",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("OUTCOME_EXCLUDES_PATHS_DESC"),
		example: t("OUTCOME_EXCLUDES_PATHS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "excludesPaths",
		title: t("EXCLUDES_PATHS"),
		type: "Selector",
		for: "Task",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("TASK_EXCLUDES_PATHS_DESC"),
		example: t("TASK_EXCLUDES_PATHS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "excludesPaths",
		title: t("EXCLUDES_PATHS"),
		type: "Selector",
		for: "Custom",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("CUSTOM_EXCLUDES_PATHS_DESC"),
		example: t("CUSTOM_EXCLUDES_PATHS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "fleetingNoteDateFormat",
		title: t("FLEETING_NOTE_DATE_FORMAT"),
		type: "Selector",
		for: "Output",
		order: 10,
		level: "Note",
		valueType: "string",
		defaultValue: "${fleetingNoteDateFormat}",
		description: t("OUTPUT_FLEETING_NOTE_DATE_FORMAT_DESC"),
		example: t("OUTPUT_FLEETING_NOTE_DATE_FORMAT_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "fleetingNoteFolder",
		title: t("FLEETING_NOTE_FOLDER"),
		type: "Selector",
		for: "Output",
		order: 8,
		level: "Note",
		valueType: "path",
		defaultValue: "${fleetingNoteFolder}",
		description: t("OUTPUT_FLEETING_NOTE_FOLDER_DESC"),
		example: t("OUTPUT_FLEETING_NOTE_FOLDER_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "fleetingNotePrefix",
		title: t("FLEETING_NOTE_PREFIX"),
		type: "Selector",
		for: "Output",
		order: 9,
		level: "Note",
		valueType: "string",
		defaultValue: "${fleetingNotePrefix}",
		description: t("OUTPUT_FLEETING_NOTE_PREFIX_DESC"),
		example: t("OUTPUT_FLEETING_NOTE_PREFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "folderPath",
		title: t("FOLDER_PATH"),
		type: "Selector",
		for: "Input",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "${inputFolder}",
		description: t("INPUT_FOLDER_PATH_DESC"),
		example: t("INPUT_FOLDER_PATH_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "folderPath",
		title: t("FOLDER_PATH"),
		type: "Selector",
		for: "Output",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "${outputFolder}",
		description: t("OUTPUT_FOLDER_PATH_DESC"),
		example: t("OUTPUT_FOLDER_PATH_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "folderPath",
		title: t("FOLDER_PATH"),
		type: "Selector",
		for: "Outcome",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "${outcomeFolder}",
		description: t("OUTCOME_FOLDER_PATH_DESC"),
		example: t("OUTCOME_FOLDER_PATH_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "folderPath",
		title: t("FOLDER_PATH"),
		type: "Selector",
		for: "Task",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "${taskFolder}",
		description: t("TASK_FOLDER_PATH_DESC"),
		example: t("TASK_FOLDER_PATH_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "folderPath",
		title: t("FOLDER_PATH"),
		type: "Selector",
		for: "Custom",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "",
		description: t("CUSTOM_FOLDER_PATH_DESC"),
		example: t("CUSTOM_FOLDER_PATH_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "includeParentFolder",
		title: t("INCLUDE_PARENT_FOLDER"),
		type: "Selector",
		for: "Outcome",
		order: 6,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("OUTCOME_INCLUDE_PARENT_FOLDER_DESC"),
		example: t("OUTCOME_INCLUDE_PARENT_FOLDER_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "isOutcomeSelector",
		title: t("IS_OUTCOME_SELECTOR"),
		type: "Selector",
		for: "Outcome",
		order: 4,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTCOME_IS_OUTCOME_SELECTOR_DESC"),
		example: t("OUTCOME_IS_OUTCOME_SELECTOR_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePostfix",
		title: t("NOTE_NAME_POSTFIX"),
		type: "Selector",
		for: "Input",
		order: 4,
		level: "Note",
		valueType: "string",
		defaultValue: "${inputNoteNamePostfix}",
		description: t("INPUT_NOTE_NAME_POSTFIX_DESC"),
		example: t("INPUT_NOTE_NAME_POSTFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePostfix",
		title: t("NOTE_NAME_POSTFIX"),
		type: "Selector",
		for: "Output",
		order: 4,
		level: "Note",
		valueType: "string",
		defaultValue: "${outputNoteNamePostfix}",
		description: t("OUTPUT_NOTE_NAME_POSTFIX_DESC"),
		example: t("OUTPUT_NOTE_NAME_POSTFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePostfix",
		title: t("NOTE_NAME_POSTFIX"),
		type: "Selector",
		for: "Outcome",
		order: 4,
		level: "Note",
		valueType: "string",
		defaultValue: "${outcomeNoteNamePostfix}",
		description: t("OUTCOME_NOTE_NAME_POSTFIX_DESC"),
		example: t("OUTCOME_NOTE_NAME_POSTFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePostfix",
		title: t("NOTE_NAME_POSTFIX"),
		type: "Selector",
		for: "Custom",
		order: 4,
		level: "Note",
		valueType: "string",
		defaultValue: "",
		description: t("CUSTOM_NOTE_NAME_POSTFIX_DESC"),
		example: t("CUSTOM_NOTE_NAME_POSTFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePrefix",
		title: t("NOTE_NAME_PREFIX"),
		type: "Selector",
		for: "Input",
		order: 3,
		level: "Note",
		valueType: "string",
		defaultValue: "${inputNoteNamePrefix}",
		description: t("INPUT_NOTE_NAME_PREFIX_DESC"),
		example: t("INPUT_NOTE_NAME_PREFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePrefix",
		title: t("NOTE_NAME_PREFIX"),
		type: "Selector",
		for: "Output",
		order: 3,
		level: "Note",
		valueType: "string",
		defaultValue: "${outputNoteNamePrefix}",
		description: t("OUTPUT_NOTE_NAME_PREFIX_DESC"),
		example: t("OUTPUT_NOTE_NAME_PREFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePrefix",
		title: t("NOTE_NAME_PREFIX"),
		type: "Selector",
		for: "Outcome",
		order: 3,
		level: "Note",
		valueType: "string",
		defaultValue: "${outcomeNoteNamePrefix}",
		description: t("OUTCOME_NOTE_NAME_PREFIX_DESC"),
		example: t("OUTCOME_NOTE_NAME_PREFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "noteNamePrefix",
		title: t("NOTE_NAME_PREFIX"),
		type: "Selector",
		for: "Custom",
		order: 3,
		level: "Note",
		valueType: "string",
		defaultValue: "",
		description: t("CUSTOM_NOTE_NAME_PREFIX_DESC"),
		example: t("CUSTOM_NOTE_NAME_PREFIX_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "optionContentTemplate",
		title: t("OPTION_CONTENT_TEMPLATE"),
		type: "Selector",
		for: "Input",
		order: 6,
		level: "Folder",
		valueType: "string",
		defaultValue: "${inputSelectorFolderOptionTemplate}",
		description: t("INPUT_OPTION_CONTENT_TEMPLATE_DESC"),
		example: t("INPUT_OPTION_CONTENT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "optionContentTemplate",
		title: t("OPTION_CONTENT_TEMPLATE"),
		type: "Selector",
		for: "Output",
		order: 6,
		level: "Folder",
		valueType: "file",
		defaultValue: "${outputSelectorFolderOptionTemplate}",
		description: t("OUTPUT_OPTION_CONTENT_TEMPLATE_DESC"),
		example: t("OUTPUT_OPTION_CONTENT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "optionContentTemplate",
		title: t("OPTION_CONTENT_TEMPLATE"),
		type: "Selector",
		for: "Task",
		order: 6,
		level: "Folder",
		valueType: "string",
		defaultValue: "${taskSelectorFolderOptionTemplate}",
		description: t("TASK_OPTION_CONTENT_TEMPLATE_DESC"),
		example: t("TASK_OPTION_CONTENT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "optionContentTemplate",
		title: t("OPTION_CONTENT_TEMPLATE"),
		type: "Selector",
		for: "Custom",
		order: 6,
		level: "Folder",
		valueType: "string",
		defaultValue: t("OPTION_TEMPLATE"),
		description: t("CUSTOM_OPTION_CONTENT_TEMPLATE_DESC"),
		example: t("CUSTOM_OPTION_CONTENT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "optionContentTemplate",
		title: t("OPTION_CONTENT_TEMPLATE"),
		type: "Selector",
		for: "Outcome",
		order: 9,
		level: "Folder",
		valueType: "string",
		defaultValue: "${outcomeSelectorFolderOptionTemplate}",
		description: t("OUTCOME_OPTION_CONTENT_TEMPLATE_DESC"),
		example: t("OUTCOME_OPTION_CONTENT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "outcomeProjectDefaultSubFolders",
		title: t("OUTCOME_PROJECT_DEFAULT_SUB_FOLDERS"),
		type: "Selector",
		for: "Outcome",
		order: 5,
		level: "Folder",
		valueType: "array",
		defaultValue: ["Demo", "Notes"],
		description: t("OUTCOME_OUTCOME_PROJECT_DEFAULT_SUB_FOLDERS_DESC"),
		example: t("OUTCOME_OUTCOME_PROJECT_DEFAULT_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "projectNameFormat",
		title: t("PROJECT_NAME_FORMAT"),
		type: "Selector",
		for: "Task",
		order: 3,
		level: "Note",
		valueType: "string",
		defaultValue: "${projectNameFormat}",
		description: t("TASK_PROJECT_NAME_FORMAT_DESC"),
		example: t("TASK_PROJECT_NAME_FORMAT_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showBasePathInOption",
		title: t("SHOW_BASE_PATH_IN_OPTION"),
		type: "Selector",
		for: "Input",
		order: 4,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("INPUT_SHOW_BASE_PATH_IN_OPTION_DESC"),
		example: t("INPUT_SHOW_BASE_PATH_IN_OPTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showBasePathInOption",
		title: t("SHOW_BASE_PATH_IN_OPTION"),
		type: "Selector",
		for: "Output",
		order: 4,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("OUTPUT_SHOW_BASE_PATH_IN_OPTION_DESC"),
		example: t("OUTPUT_SHOW_BASE_PATH_IN_OPTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showBasePathInOption",
		title: t("SHOW_BASE_PATH_IN_OPTION"),
		type: "Selector",
		for: "Task",
		order: 4,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("TASK_SHOW_BASE_PATH_IN_OPTION_DESC"),
		example: t("TASK_SHOW_BASE_PATH_IN_OPTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showBasePathInOption",
		title: t("SHOW_BASE_PATH_IN_OPTION"),
		type: "Selector",
		for: "Custom",
		order: 4,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("CUSTOM_SHOW_BASE_PATH_IN_OPTION_DESC"),
		example: t("CUSTOM_SHOW_BASE_PATH_IN_OPTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showBasePathInOption",
		title: t("SHOW_BASE_PATH_IN_OPTION"),
		type: "Selector",
		for: "Outcome",
		order: 7,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("OUTCOME_SHOW_BASE_PATH_IN_OPTION_DESC"),
		example: t("OUTCOME_SHOW_BASE_PATH_IN_OPTION_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showOptionOrder",
		title: t("SHOW_OPTION_ORDER"),
		type: "Selector",
		for: "Input",
		order: 5,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("INPUT_SHOW_OPTION_ORDER_DESC"),
		example: t("INPUT_SHOW_OPTION_ORDER_EXAMPLE"),
		imageExplain:
			"https://wafer-1257318448.cos.ap-guangzhou.myqcloud.com/20260121045522.png",
	},
	{
		name: "showOptionOrder",
		title: t("SHOW_OPTION_ORDER"),
		type: "Selector",
		for: "Output",
		order: 5,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTPUT_SHOW_OPTION_ORDER_DESC"),
		example: t("OUTPUT_SHOW_OPTION_ORDER_EXAMPLE"),
		imageExplain:
			"https://wafer-1257318448.cos.ap-guangzhou.myqcloud.com/20260121045522.png",
	},
	{
		name: "showOptionOrder",
		title: t("SHOW_OPTION_ORDER"),
		type: "Selector",
		for: "Task",
		order: 5,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("TASK_SHOW_OPTION_ORDER_DESC"),
		example: t("TASK_SHOW_OPTION_ORDER_EXAMPLE"),
		imageExplain:
			"https://wafer-1257318448.cos.ap-guangzhou.myqcloud.com/20260121045522.png",
	},
	{
		name: "showOptionOrder",
		title: t("SHOW_OPTION_ORDER"),
		type: "Selector",
		for: "Custom",
		order: 5,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("CUSTOM_SHOW_OPTION_ORDER_DESC"),
		example: t("CUSTOM_SHOW_OPTION_ORDER_EXAMPLE"),
		imageExplain:
			"https://wafer-1257318448.cos.ap-guangzhou.myqcloud.com/20260121045522.png",
	},
	{
		name: "showOptionOrder",
		title: t("SHOW_OPTION_ORDER"),
		type: "Selector",
		for: "Outcome",
		order: 8,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTCOME_SHOW_OPTION_ORDER_DESC"),
		example: t("OUTCOME_SHOW_OPTION_ORDER_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showSubFolders",
		title: t("SHOW_SUB_FOLDERS"),
		type: "Selector",
		for: "Input",
		order: 2,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("INPUT_SHOW_SUB_FOLDERS_DESC"),
		example: t("INPUT_SHOW_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showSubFolders",
		title: t("SHOW_SUB_FOLDERS"),
		type: "Selector",
		for: "Output",
		order: 2,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTPUT_SHOW_SUB_FOLDERS_DESC"),
		example: t("OUTPUT_SHOW_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showSubFolders",
		title: t("SHOW_SUB_FOLDERS"),
		type: "Selector",
		for: "Task",
		order: 2,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("TASK_SHOW_SUB_FOLDERS_DESC"),
		example: t("TASK_SHOW_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showSubFolders",
		title: t("SHOW_SUB_FOLDERS"),
		type: "Selector",
		for: "Outcome",
		order: 2,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("OUTCOME_SHOW_SUB_FOLDERS_DESC"),
		example: t("OUTCOME_SHOW_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "showSubFolders",
		title: t("SHOW_SUB_FOLDERS"),
		type: "Selector",
		for: "Custom",
		order: 2,
		level: "Folder",
		valueType: "boolean",
		defaultValue: true,
		description: t("CUSTOM_SHOW_SUB_FOLDERS_DESC"),
		example: t("CUSTOM_SHOW_SUB_FOLDERS_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "taskFolder",
		title: t("TASK_FOLDER"),
		type: "Selector",
		for: "Outcome",
		order: 1,
		level: "Folder",
		valueType: "path",
		defaultValue: "${taskFolder}",
		description: t("OUTCOME_TASK_FOLDER_DESC"),
		example: t("OUTCOME_TASK_FOLDER_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "template",
		title: t("TEMPLATE"),
		type: "Selector",
		for: "Input",
		order: 1,
		level: "Note",
		valueType: "file",
		defaultValue: "${switcherTemplate}",
		description: t("INPUT_TEMPLATE_DESC"),
		example: t("INPUT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "template",
		title: t("TEMPLATE"),
		type: "Selector",
		for: "Output",
		order: 1,
		level: "Note",
		valueType: "file",
		defaultValue: "${switcherTemplate}",
		description: t("OUTPUT_TEMPLATE_DESC"),
		example: t("OUTPUT_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "template",
		title: t("TEMPLATE"),
		type: "Selector",
		for: "Outcome",
		order: 1,
		level: "Note",
		valueType: "file",
		defaultValue: "${switcherTemplate}",
		description: t("OUTCOME_TEMPLATE_DESC"),
		example: t("OUTCOME_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "template",
		title: t("TEMPLATE"),
		type: "Selector",
		for: "Task",
		order: 1,
		level: "Note",
		valueType: "file",
		defaultValue: "${switcherTemplate}",
		description: t("TASK_TEMPLATE_DESC"),
		example: t("TASK_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "template",
		title: t("TEMPLATE"),
		type: "Selector",
		for: "Custom",
		order: 1,
		level: "Note",
		valueType: "file",
		defaultValue: "",
		description: t("CUSTOM_TEMPLATE_DESC"),
		example: t("CUSTOM_TEMPLATE_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "timestampFormat",
		title: t("TIMESTAMP_FORMAT"),
		type: "Selector",
		for: "Task",
		order: 4,
		level: "Note",
		valueType: "string",
		defaultValue: "${defaultTDLDateFormat}",
		description: t("TASK_TIMESTAMP_FORMAT_DESC"),
		example: t("TASK_TIMESTAMP_FORMAT_EXAMPLE"),
		imageExplain: "",
	},
	{
		name: "useCustomTDLName",
		title: t("USE_CUSTOM_TDL_NAME"),
		type: "Selector",
		for: "Task",
		order: 2,
		level: "Note",
		valueType: "boolean",
		defaultValue: true,
		description: t("TASK_USE_CUSTOM_TDL_NAME_DESC"),
		example: t("TASK_USE_CUSTOM_TDL_NAME_EXAMPLE"),
		imageExplain: "",
	},
];
