import { TemplateOption } from "../types/types";
import { t } from "../lang/helpers";

export const SWITCHERS_TEMPLATE_OPTIONS: TemplateOption[] = [
	{
		name: "useFullPath",
		title: t("USE_FULL_PATH"),
		type: "Switcher",
		for: "Input",
		order: 1,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("INPUT_USE_FULL_PATH_DESC"),
		example: t("INPUT_USE_FULL_PATH_EXAMPLE"),
	},
	{
		name: "useFullPath",
		title: t("USE_FULL_PATH"),
		type: "Switcher",
		for: "Output",
		order: 1,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("OUTPUT_USE_FULL_PATH_DESC"),
		example: t("OUTPUT_USE_FULL_PATH_EXAMPLE"),
	},
	{
		name: "useFullPath",
		title: t("USE_FULL_PATH"),
		type: "Switcher",
		for: "Task",
		order: 1,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("TASK_USE_FULL_PATH_DESC"),
		example: t("TASK_USE_FULL_PATH_EXAMPLE"),
	},
	{
		name: "useFullPath",
		title: t("USE_FULL_PATH"),
		type: "Switcher",
		for: "Outcome",
		order: 1,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("OUTCOME_USE_FULL_PATH_DESC"),
		example: t("OUTCOME_USE_FULL_PATH_EXAMPLE"),
	},
	{
		name: "useFullPath",
		title: t("USE_FULL_PATH"),
		type: "Switcher",
		for: "Custom",
		order: 1,
		level: "Folder",
		valueType: "boolean",
		defaultValue: false,
		description: t("CUSTOM_USE_FULL_PATH_DESC"),
		example: t("CUSTOM_USE_FULL_PATH_EXAMPLE"),
	},
	{
		name: "switchers",
		title: t("SWITCHERS"),
		type: "Switcher",
		for: "Input",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("INPUT_SWITCHERS_DESC"),
		example: t("INPUT_SWITCHERS_EXAMPLE"),
	},
	{
		name: "switchers",
		title: t("SWITCHERS"),
		type: "Switcher",
		for: "Output",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("OUTPUT_SWITCHERS_DESC"),
		example: t("OUTPUT_SWITCHERS_EXAMPLE"),
	},
	{
		name: "switchers",
		title: t("SWITCHERS"),
		type: "Switcher",
		for: "Task",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("TASK_SWITCHERS_DESC"),
		example: t("TASK_SWITCHERS_EXAMPLE"),
	},
	{
		name: "switchers",
		title: t("SWITCHERS"),
		type: "Switcher",
		for: "Outcome",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("OUTCOME_SWITCHERS_DESC"),
		example: t("OUTCOME_SWITCHERS_EXAMPLE"),
	},
	{
		name: "switchers",
		title: t("SWITCHERS"),
		type: "Switcher",
		for: "Custom",
		order: 3,
		level: "Folder",
		valueType: "array",
		defaultValue: [],
		description: t("CUSTOM_SWITCHERS_DESC"),
		example: t("CUSTOM_SWITCHERS_EXAMPLE"),
	},
	{
		name: "shareFrontMatters",
		title: t("SHARE_FRONT_MATTERS"),
		type: "Switcher",
		for: "Input",
		order: 2,
		level: "Folder",
		valueType: "object",
		defaultValue: {},
		description: t("INPUT_SHARE_FRONT_MATTERS_DESC"),
		example: t("INPUT_SHARE_FRONT_MATTERS_EXAMPLE"),
	},
	{
		name: "shareFrontMatters",
		title: t("SHARE_FRONT_MATTERS"),
		type: "Switcher",
		for: "Output",
		order: 2,
		level: "Folder",
		valueType: "object",
		defaultValue: {},
		description: t("OUTPUT_SHARE_FRONT_MATTERS_DESC"),
		example: t("OUTPUT_SHARE_FRONT_MATTERS_EXAMPLE"),
	},
	{
		name: "shareFrontMatters",
		title: t("SHARE_FRONT_MATTERS"),
		type: "Switcher",
		for: "Task",
		order: 2,
		level: "Folder",
		valueType: "object",
		defaultValue: {},
		description: t("TASK_SHARE_FRONT_MATTERS_DESC"),
		example: t("TASK_SHARE_FRONT_MATTERS_EXAMPLE"),
	},
	{
		name: "shareFrontMatters",
		title: t("SHARE_FRONT_MATTERS"),
		type: "Switcher",
		for: "Outcome",
		order: 2,
		level: "Folder",
		valueType: "object",
		defaultValue: {},
		description: t("OUTCOME_SHARE_FRONT_MATTERS_DESC"),
		example: t("OUTCOME_SHARE_FRONT_MATTERS_EXAMPLE"),
	},
	{
		name: "shareFrontMatters",
		title: t("SHARE_FRONT_MATTERS"),
		type: "Switcher",
		for: "Custom",
		order: 2,
		level: "Folder",
		valueType: "object",
		defaultValue: {},
		description: t("CUSTOM_SHARE_FRONT_MATTERS_DESC"),
		example: t("CUSTOM_SHARE_FRONT_MATTERS_EXAMPLE"),
	},
	{
		name: "defaultTemplate",
		title: t("DEFAULT_TEMPLATE"),
		type: "Switcher",
		for: "Input",
		order: 4,
		level: "Folder",
		valueType: "string",
		defaultValue: "My-TP-Input-Default",
		description: t("INPUT_DEFAULT_TEMPLATE_DESC"),
		example: t("INPUT_DEFAULT_TEMPLATE_EXAMPLE"),
	},
	{
		name: "defaultTemplate",
		title: t("DEFAULT_TEMPLATE"),
		type: "Switcher",
		for: "Output",
		order: 4,
		level: "Folder",
		valueType: "string",
		defaultValue: "My-TP-Output-Default",
		description: t("OUTPUT_DEFAULT_TEMPLATE_DESC"),
		example: t("OUTPUT_DEFAULT_TEMPLATE_EXAMPLE"),
	},
	{
		name: "defaultTemplate",
		title: t("DEFAULT_TEMPLATE"),
		type: "Switcher",
		for: "Task",
		order: 4,
		level: "Folder",
		valueType: "string",
		defaultValue: "My-TP-Task-Default",
		description: t("TASK_DEFAULT_TEMPLATE_DESC"),
		example: t("TASK_DEFAULT_TEMPLATE_EXAMPLE"),
	},
	{
		name: "defaultTemplate",
		title: t("DEFAULT_TEMPLATE"),
		type: "Switcher",
		for: "Outcome",
		order: 4,
		level: "Folder",
		valueType: "string",
		defaultValue: "My-TP-Outcome-Default",
		description: t("OUTCOME_DEFAULT_TEMPLATE_DESC"),
		example: t("OUTCOME_DEFAULT_TEMPLATE_EXAMPLE"),
	},
	{
		name: "defaultTemplate",
		title: t("DEFAULT_TEMPLATE"),
		type: "Switcher",
		for: "Custom",
		order: 4,
		level: "Folder",
		valueType: "string",
		defaultValue: "",
		description: t("CUSTOM_DEFAULT_TEMPLATE_DESC"),
		example: t("CUSTOM_DEFAULT_TEMPLATE_EXAMPLE"),
	},
];
